name: Test on dataset


on: [push, pull_request_target]

jobs:
  TestOnDataset:
    name: Run and Test on the dataset (Python ${{ matrix.python-version }} on ${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    runs-on: ${{ matrix.os }}
    
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:        
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: '${{ secrets.ONDRA_PAT }}'
        submodules: 'true'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Test with pytest
      run: python3 ParseDocument.py > test_stats_${{matrix.python-version}}.txt

    - name: Upload Unit Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test stats (Python ${{ matrix.python-version }})
        path: test_stats_${{matrix.python-version}}.txt

